# Generated by Django 2.1.4 on 2019-06-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='token',
            table='token',
        ),
    ]
