# Generated by Django 2.1.4 on 2019-01-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20181231_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songlist',
        ),
        migrations.RemoveField(
            model_name='songlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Songlist',
        ),
    ]
